// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHK73K7uXSWzGzJ-BAOz9NjlDtWcsjs60',
    appId: '1:695513250145:web:739c8e36129459f1d2ed20',
    messagingSenderId: '695513250145',
    projectId: 'womens-courtyard',
    authDomain: 'womens-courtyard.firebaseapp.com',
    storageBucket: 'womens-courtyard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwlr2gWN9npbvERdPxbRgAp2XL14FZfTU',
    appId: '1:695513250145:android:5f1623053b78004dd2ed20',
    messagingSenderId: '695513250145',
    projectId: 'womens-courtyard',
    storageBucket: 'womens-courtyard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn9I-f-ucN_WtGGHbcQzgv_K1Yt4XMhA0',
    appId: '1:695513250145:ios:6a6a5ba13d886c27d2ed20',
    messagingSenderId: '695513250145',
    projectId: 'womens-courtyard',
    storageBucket: 'womens-courtyard.appspot.com',
    iosClientId:
        '695513250145-9170fi3iooifo2dg6ple3sifoi6ga0bu.apps.googleusercontent.com',
    iosBundleId: 'com.technion.android.womensCourtyard',
  );
}
